package com.mrsummaries.interactiveink.canvas

import android.view.MotionEvent
import androidx.ink.authoring.InProgressStrokeId
import androidx.ink.strokes.Stroke
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch

/**
 * InkTool
 *
 * Enumeration of the tools a user can activate in the [InkToolbar].
 * Extending this enum (e.g. adding `Highlighter`, `Lasso`) is the intended
 * approach for adding new tool types without modifying existing logic.
 */
enum class InkTool {
    /** Standard pressure-sensitive ink pen. */
    Pen,

    /** Stroke eraser; removes whole strokes that the tip crosses. */
    Eraser,
}

/**
 * InkViewModel
 *
 * The single source of truth for:
 *  - The list of *committed* (finished) [Stroke]s that make up the current note page.
 *  - The currently active [InkTool].
 *  - Undo history (simple last-in / first-out stack for this foundational phase).
 *
 * This ViewModel intentionally has **no** dependency on networking, ML, or storage.
 * Those will be wired in via dependency injection once the corresponding modules
 * are ready. The ViewModel exposes [StateFlow]s so that both Compose UI and future
 * non-Compose consumers can observe state reactively.
 *
 * ## Integration points for future modules
 *  - **CRDT sync**: override [onStrokeFinished] / [deleteStrokes] to emit operations
 *    to a CRDT document manager.
 *  - **ML recognition**: collect [committedStrokes] changes and schedule a
 *    handwriting-recognition job on a background dispatcher.
 *  - **Storage**: persist [committedStrokes] to Room whenever the list changes.
 */
class InkViewModel : ViewModel() {

    // ── Committed strokes ────────────────────────────────────────────────────

    /**
     * Backing store for committed strokes. A [List] is used rather than a [Set]
     * to preserve insertion order (important for layered rendering and undo).
     *
     * Exposed as [StateFlow] so collectors are always given the full current list,
     * which simplifies re-rendering logic (no need to track deltas separately).
     */
    private val _committedStrokes = MutableStateFlow<List<CommittedStroke>>(emptyList())
    val committedStrokes: StateFlow<List<CommittedStroke>> = _committedStrokes.asStateFlow()

    // ── Undo stack ───────────────────────────────────────────────────────────

    /**
     * Simple undo stack holding [UndoEntry] values. Each entry captures the
     * state needed to reverse a single user action (add or delete strokes).
     *
     * A full undo/redo system would use a bi-directional command stack; this
     * implementation provides undo-only as the foundational building block.
     */
    private val undoStack = ArrayDeque<UndoEntry>()

    // ── Active tool ──────────────────────────────────────────────────────────

    private val _activeTool = MutableStateFlow(InkTool.Pen)
    val activeTool: StateFlow<InkTool> = _activeTool.asStateFlow()

    // ── Gesture state ────────────────────────────────────────────────────────

    /**
     * Scratch-out classifier instance. Stateless between gestures; each new
     * gesture feeds a fresh batch of points into [ScratchOutClassifier.classify].
     */
    private val scratchOutClassifier = ScratchOutClassifier()

    /**
     * Collects [MotionEvent] points for the current finger gesture. Points are
     * accumulated from [ACTION_DOWN] to [ACTION_UP] / [ACTION_CANCEL] and then
     * passed to the classifier as a single batch.
     */
    private val currentFingerGesturePoints = mutableListOf<GesturePoint>()

    // ── Public API ───────────────────────────────────────────────────────────

    /**
     * Called by [InkCanvasScreen] (via [InkCanvas]) when the Android Ink API
     * reports that a stroke has been committed (stylus lifted).
     *
     * The [Stroke] is wrapped in a [CommittedStroke] with a stable ID and appended
     * to the committed list. An undo entry is pushed so the user can reverse the add.
     *
     * @param strokeId  The [InProgressStrokeId] assigned by [InProgressStrokesView].
     * @param stroke    The finished, immutable [Stroke] object.
     */
    fun onStrokeFinished(strokeId: InProgressStrokeId, stroke: Stroke) {
        viewModelScope.launch {
            val committed = CommittedStroke(id = strokeId.toString(), stroke = stroke)
            val updated = _committedStrokes.value + committed
            _committedStrokes.value = updated
            undoStack.addLast(UndoEntry.AddStroke(committed))
        }
    }

    /**
     * Called by [TouchRouter] (inside [InkCanvasScreen]) for every [MotionEvent]
     * generated by a finger pointer. Points are accumulated until the gesture ends,
     * then classified as a scratch-out or ignored.
     *
     * @param event  The raw [MotionEvent]; only finger tool-type events should be sent.
     */
    fun onFingerMotionEvent(event: MotionEvent) {
        when (event.actionMasked) {
            MotionEvent.ACTION_DOWN -> {
                currentFingerGesturePoints.clear()
                currentFingerGesturePoints.add(GesturePoint(event.x, event.y, event.eventTime))
            }

            MotionEvent.ACTION_MOVE -> {
                // Capture all historical points in the batch for accurate classification.
                for (i in 0 until event.historySize) {
                    currentFingerGesturePoints.add(
                        GesturePoint(
                            x = event.getHistoricalX(i),
                            y = event.getHistoricalY(i),
                            timestamp = event.getHistoricalEventTime(i),
                        ),
                    )
                }
                currentFingerGesturePoints.add(GesturePoint(event.x, event.y, event.eventTime))
            }

            MotionEvent.ACTION_UP -> {
                currentFingerGesturePoints.add(GesturePoint(event.x, event.y, event.eventTime))
                classifyAndApplyFingerGesture()
                currentFingerGesturePoints.clear()
            }

            MotionEvent.ACTION_CANCEL -> {
                currentFingerGesturePoints.clear()
            }
        }
    }

    /**
     * Removes a set of strokes from the committed list (e.g. after a scratch-out
     * gesture or an explicit eraser pass).
     *
     * Pushes a [UndoEntry.DeleteStrokes] so the deletions can be undone.
     *
     * @param strokeIds  The [CommittedStroke.id] values to remove.
     */
    fun deleteStrokes(strokeIds: Set<String>) {
        if (strokeIds.isEmpty()) return
        viewModelScope.launch {
            val current = _committedStrokes.value
            val deleted = current.filter { it.id in strokeIds }
            if (deleted.isEmpty()) return@launch
            _committedStrokes.value = current.filterNot { it.id in strokeIds }
            undoStack.addLast(UndoEntry.DeleteStrokes(deleted))
        }
    }

    /** Selects the active [InkTool]. */
    fun selectTool(tool: InkTool) {
        _activeTool.value = tool
    }

    /**
     * Undoes the most recent add or delete action.
     *
     * - Undoing an *add* removes the last added stroke.
     * - Undoing a *delete* re-inserts the deleted strokes at the end of the list
     *   (original position is not preserved in this foundational implementation).
     */
    fun undo() {
        viewModelScope.launch {
            val entry = undoStack.removeLastOrNull() ?: return@launch
            when (entry) {
                is UndoEntry.AddStroke -> {
                    _committedStrokes.value =
                        _committedStrokes.value.filterNot { it.id == entry.stroke.id }
                }
                is UndoEntry.DeleteStrokes -> {
                    _committedStrokes.value = _committedStrokes.value + entry.strokes
                }
            }
        }
    }

    // ── Internal helpers ─────────────────────────────────────────────────────

    private fun classifyAndApplyFingerGesture() {
        if (currentFingerGesturePoints.size < 2) return

        val result = scratchOutClassifier.classify(currentFingerGesturePoints)
        if (result is GestureResult.ScratchOut) {
            val handler = ScratchOutDeletionHandler(_committedStrokes.value)
            val ids = handler.findIntersectingStrokes(result.boundingBox)
            if (ids.isNotEmpty()) {
                deleteStrokes(ids)
                // TODO: signal ML text-reflow engine once that module is integrated.
            }
        }
        // Other gesture types (tap, long-press, pan) can be handled here in future.
    }
}

// ---------------------------------------------------------------------------
// Data classes
// ---------------------------------------------------------------------------

/**
 * A committed (finished) stroke plus a stable string identifier.
 *
 * The [id] is derived from [InProgressStrokeId.toString()] at the time the
 * stroke is committed. It is used as the stable key for CRDT operations,
 * undo entries, and bounding-box intersection checks.
 *
 * @property id     Stable unique identifier for this stroke on this device.
 * @property stroke The immutable [Stroke] value from the Android Ink API.
 */
data class CommittedStroke(
    val id: String,
    val stroke: Stroke,
)

/**
 * Sealed class representing a single undoable action.
 *
 * Extending this with `Redo` or `Transform` variants would enable a full
 * undo/redo command stack without breaking existing consumers.
 */
sealed class UndoEntry {
    data class AddStroke(val stroke: CommittedStroke) : UndoEntry()
    data class DeleteStrokes(val strokes: List<CommittedStroke>) : UndoEntry()
}
